### ISSUE TITLE
Call to undefined function Zhuqipeng\LaravelHprose\str_is()

### ISSUE THREAD

**Issue by tanjhysj0** [zhuqipeng/laravel-hprose#5]
`serlon@serlon-PC:~/PhpstormProjects/laraveldemo$ composer require "zhuqipeng/laravel-hprose:v1.0-alpha"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Downgrading zhuqipeng/laravel-hprose (v1.0.2 => v1.0-alpha): Downloading (100%)         
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Error 

  Call to undefined function Zhuqipeng\LaravelHprose\str_is()

  at vendor/zhuqipeng/laravel-hprose/src/ServiceProvider.php:93
    89|     protected function setupRoute()
    90|     {
    91|         $source = realpath(__DIR__ . '/route.php');
    92| 
  > 93|         if (str_is('5.2.*', app()::VERSION)) {
    94|             $targetPath = base_path('app/Http/rpc.php');
    95|         } else {
    96|             $targetPath = base_path('routes/rpc.php');
    97|         }

      +8 vendor frames 
  9   artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.
`

**Comment by zhuqipeng** [comment]
在 Laravel 6.x 版本中，所有的 str_ 和 array_ 辅助函数都已经从框架中移除，扩展 laravel-hprose 中用到了 str_is() 函数，所以会报错。详情可查看 https://learnku.com/docs/laravel/6.x/upgrade/5122#a1ff39

目前 laravel-hprose 还没在 Laravel 6.x 版本中测试过，建议先不要在此版本中使用。

**Comment by xpader** [comment]
现在 Laravel 8.5 版本也不支持？？？还是有这个错。

**Comment by zhuqipeng** [comment]
> 现在 Laravel 8.5 版本也不支持？？？还是有这个错。

不支持呢，此扩展后续不再更新，不建议在项目中使用，但可作为参考 😊 @xpader
